#!/usr/bin/env bash
set -euo pipefail

version=""
release_dir=""
output_path=""
public_key=""

usage() {
  cat <<'USAGE'
Render a Nix expression for the published Loopwire binary package.

Usage:
  render-nix-release-package.sh --version VERSION --release-dir DIR --output PATH [--public-key FILE]

The release directory must contain:
  loopwire-linux-x86_64.tar.gz
  loopwire-linux-aarch64.tar.gz
  SHA256SUMS

When --public-key is provided, SHA256SUMS.sig is also required and verified before rendering.
USAGE
}

fail() {
  echo "render-nix-release-package: $*" >&2
  exit 1
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --version)
      version="${2:?missing value for --version}"
      shift 2
      ;;
    --release-dir)
      release_dir="${2:?missing value for --release-dir}"
      shift 2
      ;;
    --output)
      output_path="${2:?missing value for --output}"
      shift 2
      ;;
    --public-key)
      public_key="${2:?missing value for --public-key}"
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      fail "unknown argument: $1"
      ;;
  esac
done

[ -n "$version" ] || fail "missing --version VERSION"
[ -n "$release_dir" ] || fail "missing --release-dir DIR"
[ -n "$output_path" ] || fail "missing --output PATH"

version_pattern='^[0-9]+[.][0-9]+[.][0-9]+([.-][0-9A-Za-z][0-9A-Za-z.-]*)?$'
if [[ ! "$version" =~ $version_pattern ]]; then
  fail "version must be semver without a leading v or path syntax: $version"
fi

case "$output_path" in
  *$'\n'* | *$'\r'*)
    fail "output path must not contain newlines"
    ;;
esac

release_dir="${release_dir%/}"
[ -d "$release_dir" ] || fail "missing release directory: $release_dir"
[ -f "$release_dir/SHA256SUMS" ] || fail "missing SHA256SUMS in release directory: $release_dir"
command -v node >/dev/null 2>&1 || fail "node is required"
command -v sha256sum >/dev/null 2>&1 || fail "sha256sum is required"

asset_hash() {
  asset="$1"
  label="$2"

  [ -f "$release_dir/$asset" ] || fail "missing $label asset: $release_dir/$asset"
  if [ -n "$public_key" ]; then
    bash scripts/verify-release-asset-checksum.sh \
      --release-dir "$release_dir" \
      --asset "$asset" \
      --public-key "$public_key" \
      --label "$label" >/dev/null
  fi

  entry_count="$(awk -v asset="$asset" '$2 == asset { count++ } END { print count + 0 }' "$release_dir/SHA256SUMS")"
  case "$entry_count" in
    1)
      ;;
    0)
      fail "SHA256SUMS is missing $label entry: $asset"
      ;;
    *)
      fail "SHA256SUMS has duplicate $label entries: $asset"
      ;;
  esac

  hex_hash="$(awk -v asset="$asset" '$2 == asset { print $1 }' "$release_dir/SHA256SUMS")"
  case "$hex_hash" in
    *[!0-9A-Fa-f]* | "")
      fail "SHA256SUMS has an invalid $label hash: $hex_hash"
      ;;
  esac
  [ "${#hex_hash}" -eq 64 ] || fail "SHA256SUMS $label hash must be 64 hex characters"

  tmp_check="$(mktemp)"
  cleanup_check() {
    rm -f "$tmp_check"
  }
  trap cleanup_check RETURN
  awk -v asset="$asset" '$2 == asset { print }' "$release_dir/SHA256SUMS" >"$tmp_check"
  (cd "$release_dir" && sha256sum --check "$tmp_check" >/dev/null)

  node -e '
const hash = process.argv[1];
if (!/^[0-9a-f]{64}$/i.test(hash)) process.exit(2);
process.stdout.write(`sha256-${Buffer.from(hash, "hex").toString("base64")}`);
' "$hex_hash"
}

x86_hash="$(asset_hash "loopwire-linux-x86_64.tar.gz" "x86_64 release")"
aarch64_hash="$(asset_hash "loopwire-linux-aarch64.tar.gz" "aarch64 release")"
tmp_output="$(mktemp)"
cleanup_output() {
  rm -f "$tmp_output"
}
trap cleanup_output EXIT

cat >"$tmp_output" <<NIX
# Generated by scripts/render-nix-release-package.sh.
# Build from the Loopwire repository root with:
#   nix build -f ${output_path} --arg loopwireSrc ./.
{ pkgs ? import <nixpkgs> { system = builtins.currentSystem; }
, loopwireSrc ? ./.
}:

pkgs.callPackage (loopwireSrc + "/packaging/nix/loopwire-bin.nix") {
  version = "${version}";
  hashes = {
    x86_64-linux = "${x86_hash}";
    aarch64-linux = "${aarch64_hash}";
  };
}
NIX

mkdir -p "$(dirname "$output_path")"
cp "$tmp_output" "$output_path"
echo "Rendered $output_path"
